### ISSUE TITLE
FAIR project assessment: Architecting Attribution

### ISSUE THREAD

**Issue by kristiholmes** [data2health/resource-discovery#9]
Complete lightweight FAIR assessment and future steps for each project in the RD core. https://www.go-fair.org/fair-principles/

**Comment by nicolevasilevsky** [comment]
@kristiholmes and @LisaOKeefe1 
could we work on this together in real time during our call scheduled on Jan 16?

**Comment by nicolevasilevsky** [comment]
the call was canceled on the 16th, let's aim for the next call

**Comment by nicolevasilevsky** [comment]
Decision: wait until after Kristi's call with Ken on 01/31/20. @kristiholmes should follow up

**Comment by kristiholmes** [comment]
completed by @nicolevasilevsky at https://docs.google.com/spreadsheets/d/1GLWMMAiS_mV32Q2d8aRSjXc95Ga3pgzMHR2pWQYMClE/edit#gid=1957152089
